name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      continue-on-error: true
      run: |
        pip install flake8
        flake8 src/ tools/
    - name: Run tests
      continue-on-error: true
      run: |
        pytest --maxfail=1 --disable-warnings -q
